#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal_SOFD.LORA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LORA_SOFD")]
	public partial class LoraDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LoraDataContext() : 
				base(global::Dal_SOFD.Properties.Settings.Default.LORA_SOFDConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LoraDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoraDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoraDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoraDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_ad_user_creation> v_ad_user_creations
		{
			get
			{
				return this.GetTable<v_ad_user_creation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_ad_user_creation")]
	public partial class v_ad_user_creation
	{
		
		private int _Opus_id;
		
		private string _Fullname;
		
		private string _Firstname;
		
		private string _Lastname;
		
		private string _Cpr;
		
		private string _Position;
		
		private string _Orgunit;
		
		private int _Orgunit_losid_fk;
		
		private System.Nullable<System.DateTime> _Ans_dato;
		
		private System.Nullable<System.DateTime> _Fra_dato;
		
		private bool _Is_Manager;
		
		private string _User_fk;
		
		private string _samaccount;
		
		public v_ad_user_creation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opus_id", DbType="Int NOT NULL")]
		public int Opus_id
		{
			get
			{
				return this._Opus_id;
			}
			set
			{
				if ((this._Opus_id != value))
				{
					this._Opus_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cpr", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Cpr
		{
			get
			{
				return this._Cpr;
			}
			set
			{
				if ((this._Cpr != value))
				{
					this._Cpr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orgunit", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Orgunit
		{
			get
			{
				return this._Orgunit;
			}
			set
			{
				if ((this._Orgunit != value))
				{
					this._Orgunit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orgunit_losid_fk", DbType="Int NOT NULL")]
		public int Orgunit_losid_fk
		{
			get
			{
				return this._Orgunit_losid_fk;
			}
			set
			{
				if ((this._Orgunit_losid_fk != value))
				{
					this._Orgunit_losid_fk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ans_dato", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ans_dato
		{
			get
			{
				return this._Ans_dato;
			}
			set
			{
				if ((this._Ans_dato != value))
				{
					this._Ans_dato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fra_dato", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fra_dato
		{
			get
			{
				return this._Fra_dato;
			}
			set
			{
				if ((this._Fra_dato != value))
				{
					this._Fra_dato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Manager", DbType="Bit NOT NULL")]
		public bool Is_Manager
		{
			get
			{
				return this._Is_Manager;
			}
			set
			{
				if ((this._Is_Manager != value))
				{
					this._Is_Manager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_fk", DbType="NVarChar(200)")]
		public string User_fk
		{
			get
			{
				return this._User_fk;
			}
			set
			{
				if ((this._User_fk != value))
				{
					this._User_fk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_samaccount", DbType="NVarChar(50)")]
		public string samaccount
		{
			get
			{
				return this._samaccount;
			}
			set
			{
				if ((this._samaccount != value))
				{
					this._samaccount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
