#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ITBrugeroprettelse.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ITBrugeroprettelse")]
	public partial class DataClassITBrugeroprettelseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSkolekode(Skolekode instance);
    partial void UpdateSkolekode(Skolekode instance);
    partial void DeleteSkolekode(Skolekode instance);
    partial void InsertAnsatUdenADBruger(AnsatUdenADBruger instance);
    partial void UpdateAnsatUdenADBruger(AnsatUdenADBruger instance);
    partial void DeleteAnsatUdenADBruger(AnsatUdenADBruger instance);
    #endregion
		
		public DataClassITBrugeroprettelseDataContext() : 
				base(global::DAL.ITBrugeroprettelse.Properties.Settings.Default.ITBrugeroprettelseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassITBrugeroprettelseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassITBrugeroprettelseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassITBrugeroprettelseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassITBrugeroprettelseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Skolekode> Skolekodes
		{
			get
			{
				return this.GetTable<Skolekode>();
			}
		}
		
		public System.Data.Linq.Table<AnsatUdenADBruger> AnsatUdenADBrugers
		{
			get
			{
				return this.GetTable<AnsatUdenADBruger>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Skolekode")]
	public partial class Skolekode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SystemID;
		
		private string _Skole;
		
		private string _Insttutionsnummer;
		
		private bool _Deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystemIDChanging(int value);
    partial void OnSystemIDChanged();
    partial void OnSkoleChanging(string value);
    partial void OnSkoleChanged();
    partial void OnInsttutionsnummerChanging(string value);
    partial void OnInsttutionsnummerChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public Skolekode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SystemID
		{
			get
			{
				return this._SystemID;
			}
			set
			{
				if ((this._SystemID != value))
				{
					this.OnSystemIDChanging(value);
					this.SendPropertyChanging();
					this._SystemID = value;
					this.SendPropertyChanged("SystemID");
					this.OnSystemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skole", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Skole
		{
			get
			{
				return this._Skole;
			}
			set
			{
				if ((this._Skole != value))
				{
					this.OnSkoleChanging(value);
					this.SendPropertyChanging();
					this._Skole = value;
					this.SendPropertyChanged("Skole");
					this.OnSkoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Insttutionsnummer", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Insttutionsnummer
		{
			get
			{
				return this._Insttutionsnummer;
			}
			set
			{
				if ((this._Insttutionsnummer != value))
				{
					this.OnInsttutionsnummerChanging(value);
					this.SendPropertyChanging();
					this._Insttutionsnummer = value;
					this.SendPropertyChanged("Insttutionsnummer");
					this.OnInsttutionsnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnsatUdenADBruger")]
	public partial class AnsatUdenADBruger : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SystemID;
		
		private string _PersonFirstname;
		
		private string _PersonSurname;
		
		private string _PersonName;
		
		private string _PersonCpr;
		
		private string _EmployeeId;
		
		private string _AffiliationPositionName;
		
		private string _OrgUnitName;
		
		private System.DateTime _DateTimeStamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystemIDChanging(int value);
    partial void OnSystemIDChanged();
    partial void OnPersonFirstnameChanging(string value);
    partial void OnPersonFirstnameChanged();
    partial void OnPersonSurnameChanging(string value);
    partial void OnPersonSurnameChanged();
    partial void OnPersonNameChanging(string value);
    partial void OnPersonNameChanged();
    partial void OnPersonCprChanging(string value);
    partial void OnPersonCprChanged();
    partial void OnEmployeeIdChanging(string value);
    partial void OnEmployeeIdChanged();
    partial void OnAffiliationPositionNameChanging(string value);
    partial void OnAffiliationPositionNameChanged();
    partial void OnOrgUnitNameChanging(string value);
    partial void OnOrgUnitNameChanged();
    partial void OnDateTimeStampChanging(System.DateTime value);
    partial void OnDateTimeStampChanged();
    #endregion
		
		public AnsatUdenADBruger()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SystemID
		{
			get
			{
				return this._SystemID;
			}
			set
			{
				if ((this._SystemID != value))
				{
					this.OnSystemIDChanging(value);
					this.SendPropertyChanging();
					this._SystemID = value;
					this.SendPropertyChanged("SystemID");
					this.OnSystemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonFirstname", DbType="NVarChar(300)")]
		public string PersonFirstname
		{
			get
			{
				return this._PersonFirstname;
			}
			set
			{
				if ((this._PersonFirstname != value))
				{
					this.OnPersonFirstnameChanging(value);
					this.SendPropertyChanging();
					this._PersonFirstname = value;
					this.SendPropertyChanged("PersonFirstname");
					this.OnPersonFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonSurname", DbType="NVarChar(300)")]
		public string PersonSurname
		{
			get
			{
				return this._PersonSurname;
			}
			set
			{
				if ((this._PersonSurname != value))
				{
					this.OnPersonSurnameChanging(value);
					this.SendPropertyChanging();
					this._PersonSurname = value;
					this.SendPropertyChanged("PersonSurname");
					this.OnPersonSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonName", DbType="NVarChar(500)")]
		public string PersonName
		{
			get
			{
				return this._PersonName;
			}
			set
			{
				if ((this._PersonName != value))
				{
					this.OnPersonNameChanging(value);
					this.SendPropertyChanging();
					this._PersonName = value;
					this.SendPropertyChanged("PersonName");
					this.OnPersonNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonCpr", DbType="NVarChar(50)")]
		public string PersonCpr
		{
			get
			{
				return this._PersonCpr;
			}
			set
			{
				if ((this._PersonCpr != value))
				{
					this.OnPersonCprChanging(value);
					this.SendPropertyChanging();
					this._PersonCpr = value;
					this.SendPropertyChanged("PersonCpr");
					this.OnPersonCprChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="NVarChar(50)")]
		public string EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AffiliationPositionName", DbType="NVarChar(200)")]
		public string AffiliationPositionName
		{
			get
			{
				return this._AffiliationPositionName;
			}
			set
			{
				if ((this._AffiliationPositionName != value))
				{
					this.OnAffiliationPositionNameChanging(value);
					this.SendPropertyChanging();
					this._AffiliationPositionName = value;
					this.SendPropertyChanged("AffiliationPositionName");
					this.OnAffiliationPositionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgUnitName", DbType="NVarChar(200)")]
		public string OrgUnitName
		{
			get
			{
				return this._OrgUnitName;
			}
			set
			{
				if ((this._OrgUnitName != value))
				{
					this.OnOrgUnitNameChanging(value);
					this.SendPropertyChanging();
					this._OrgUnitName = value;
					this.SendPropertyChanged("OrgUnitName");
					this.OnOrgUnitNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime NOT NULL")]
		public System.DateTime DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this.OnDateTimeStampChanging(value);
					this.SendPropertyChanging();
					this._DateTimeStamp = value;
					this.SendPropertyChanged("DateTimeStamp");
					this.OnDateTimeStampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
