//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Web
{


	public partial class Createuser
	{

		/// <summary>
		/// RadStyleSheetManager1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadStyleSheetManager RadStyleSheetManager1;

		/// <summary>
		/// form1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;

		/// <summary>
		/// RadScriptManager1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadScriptManager RadScriptManager1;

		/// <summary>
		/// RadAjaxLoadingPanel1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadAjaxLoadingPanel RadAjaxLoadingPanel1;

		/// <summary>
		/// form_panel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel form_panel;

		/// <summary>
		/// lblTotaleFatale control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblTotaleFatale;

		/// <summary>
		/// CBOpus_medarbejdernr control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadComboBox CBOpus_medarbejdernr;

		/// <summary>
		/// TxbFornavn control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbFornavn;

		/// <summary>
		/// TxbEfternavn control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbEfternavn;

		/// <summary>
		/// TxbVistnavn control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbVistnavn;

		/// <summary>
		/// LblStilling control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel LblStilling;

		/// <summary>
		/// CbCoworkerSamaccount control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadComboBox CbCoworkerSamaccount;

		/// <summary>
		/// ErrorSkype control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorSkype;

		/// <summary>
		/// RbIsSkype control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsSkype;

		/// <summary>
		/// panelSkype control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelSkype;

		/// <summary>
		/// ErrorRingGruppe control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorRingGruppe;

		/// <summary>
		/// RbIsRingegruppe control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsRingegruppe;

		/// <summary>
		/// panelRingeGrupppe control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelRingeGrupppe;

		/// <summary>
		/// TxbRingegruppeNummer control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbRingegruppeNummer;

		/// <summary>
		/// TxbMobilNummer control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbMobilNummer;

		/// <summary>
		/// ErrorDistributionslister control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorDistributionslister;

		/// <summary>
		/// RbIsDistributionslister control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsDistributionslister;

		/// <summary>
		/// panelDistributionslister control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelDistributionslister;

		/// <summary>
		/// TxbDistributionslisterNavne control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbDistributionslisterNavne;

		/// <summary>
		/// ErrorFallespostkasser control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorFallespostkasser;

		/// <summary>
		/// RbIsFaellespostkasser control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsFaellespostkasser;

		/// <summary>
		/// panelFallespostkasser control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelFallespostkasser;

		/// <summary>
		/// TxbFaellespostkasserNavne control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbFaellespostkasserNavne;

		/// <summary>
		/// ErrorCura control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorCura;

		/// <summary>
		/// RbIsCura control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsCura;

		/// <summary>
		/// panelCura control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelCura;

		/// <summary>
		/// ErrorCuraRole control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorCuraRole;

		/// <summary>
		/// DdlCuraBrugerRolle control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadDropDownList DdlCuraBrugerRolle;

		/// <summary>
		/// btn_add_cura_rolle control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton btn_add_cura_rolle;

		/// <summary>
		/// grid_curaRoles control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadGrid grid_curaRoles;

		/// <summary>
		/// panelCuraPlanner control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelCuraPlanner;

		/// <summary>
		/// ErrorCuraPlaner control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorCuraPlaner;

		/// <summary>
		/// RbIsCuraPlanner control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsCuraPlanner;

		/// <summary>
		/// panelCuraFMK control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelCuraFMK;

		/// <summary>
		/// ErrorRbIsCuraFMK control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorRbIsCuraFMK;

		/// <summary>
		/// RbIsCuraFMK control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsCuraFMK;

		/// <summary>
		/// panelCuraFMKID control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelCuraFMKID;

		/// <summary>
		/// TxbCuraFMKID control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbCuraFMKID;

		/// <summary>
		/// panelCuraORGLOG control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelCuraORGLOG;

		/// <summary>
		/// ErrorCuraLOrg control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorCuraLOrg;

		/// <summary>
		/// ddl_curaLOrg control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadDropDownList ddl_curaLOrg;

		/// <summary>
		/// btn_add_curaLOrg control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton btn_add_curaLOrg;

		/// <summary>
		/// grid_curaLOrg control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadGrid grid_curaLOrg;

		/// <summary>
		/// ErrorRollebaseret control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorRollebaseret;

		/// <summary>
		/// RbIsRollebaseret control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsRollebaseret;

		/// <summary>
		/// PanelRollebaseret control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelRollebaseret;

		/// <summary>
		/// ComboRollebaseret control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadComboBox ComboRollebaseret;

		/// <summary>
		/// PanelRollebaseret_Leder control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelRollebaseret_Leder;

		/// <summary>
		/// TxbRollebaseretProfitcenterAnsvar control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbRollebaseretProfitcenterAnsvar;

		/// <summary>
		/// ErrorRollebaseretLeder control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorRollebaseretLeder;

		/// <summary>
		/// RbRollebaseretFaktura_Leder control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbRollebaseretFaktura_Leder;

		/// <summary>
		/// PanelRollebaseret_LederBogfoering control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelRollebaseret_LederBogfoering;

		/// <summary>
		/// TxbRollebaseretProfitcenter_LederBogfoering control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbRollebaseretProfitcenter_LederBogfoering;

		/// <summary>
		/// TxbRollebaseret_LederBogfoeringEAN control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbRollebaseret_LederBogfoeringEAN;

		/// <summary>
		/// PanelLoenPersonale control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelLoenPersonale;

		/// <summary>
		/// ErrorRollebaseretLederSeeOther control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorRollebaseretLederSeeOther;

		/// <summary>
		/// RbIsLeaderAbleToSeeOther control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsLeaderAbleToSeeOther;

		/// <summary>
		/// PanelRollebaseretSeAndre control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelRollebaseretSeAndre;

		/// <summary>
		/// TxbRollebaseret_SeAndre_OrgEnhed control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbRollebaseret_SeAndre_OrgEnhed;

		/// <summary>
		/// PanelAdministrativMedarbejder control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelAdministrativMedarbejder;

		/// <summary>
		/// ErrorRollebaseretAdministrativOpg control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorRollebaseretAdministrativOpg;

		/// <summary>
		/// BtnRollebaseretAdmMedarb_OekonomiOpg control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton BtnRollebaseretAdmMedarb_OekonomiOpg;

		/// <summary>
		/// PanelOpusOpg_Administrativ control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelOpusOpg_Administrativ;

		/// <summary>
		/// TxbOpusOpg_Administrativ_Profitcenter control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbOpusOpg_Administrativ_Profitcenter;

		/// <summary>
		/// TxbRollebaseretAdmMedarb_EAN control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbRollebaseretAdmMedarb_EAN;

		/// <summary>
		/// PanelRollebaseretAdmMedarb_LoenPersonale control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelRollebaseretAdmMedarb_LoenPersonale;

		/// <summary>
		/// BtnRollebaseretAdmMedarb_LoenPersonale control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton BtnRollebaseretAdmMedarb_LoenPersonale;

		/// <summary>
		/// PanelRollebaseretAdmMedarb_OrgEnh control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelRollebaseretAdmMedarb_OrgEnh;

		/// <summary>
		/// TxbRollebaseretAdmMedarb_OrgEnh control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbRollebaseretAdmMedarb_OrgEnh;

		/// <summary>
		/// PanelRollebaseretAdmMedarb_Andet control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelRollebaseretAdmMedarb_Andet;

		/// <summary>
		/// BtnRollebaseretAdmMedarb_Andet control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton BtnRollebaseretAdmMedarb_Andet;

		/// <summary>
		/// PanelRollebaseretAdmMedarb_Rettigheder control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelRollebaseretAdmMedarb_Rettigheder;

		/// <summary>
		/// TxbRollebaseretAdmMedarb_Andet control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbRollebaseretAdmMedarb_Andet;

		/// <summary>
		/// PanelRollebaseretAndet control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelRollebaseretAndet;

		/// <summary>
		/// TxbRollebaseretAndet control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbRollebaseretAndet;

		/// <summary>
		/// ErrorKMDInstitution control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorKMDInstitution;

		/// <summary>
		/// RbIsKmdInstitution control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsKmdInstitution;

		/// <summary>
		/// PanelKmdInstitution control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelKmdInstitution;

		/// <summary>
		/// ComboKmdInstitution control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadComboBox ComboKmdInstitution;

		/// <summary>
		/// PanelKmdInsttution_Institutionsnummer control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel PanelKmdInsttution_Institutionsnummer;

		/// <summary>
		/// TxtBoxKmdInsttution_Institutionsnummer control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxtBoxKmdInsttution_Institutionsnummer;

		/// <summary>
		/// ErrorKMDBruger control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorKMDBruger;

		/// <summary>
		/// RbIsKMDbruger control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsKMDbruger;

		/// <summary>
		/// panelKMD control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panelKMD;

		/// <summary>
		/// TxbKMDUserProfiles control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbKMDUserProfiles;

		/// <summary>
		/// ErrorTargit control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorTargit;

		/// <summary>
		/// RbIsTargit control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsTargit;

		/// <summary>
		/// ErrorEducaPersonale control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorEducaPersonale;

		/// <summary>
		/// RbIsEducaPersonale control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbIsEducaPersonale;

		/// <summary>
		/// panel_educapersonale control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panel_educapersonale;

		/// <summary>
		/// TxbEducaPersonale_unilogin control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbEducaPersonale_unilogin;

		/// <summary>
		/// TxbEducaPersonale_skolekode control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbEducaPersonale_skolekode;

		/// <summary>
		/// ErrorEducaPersonale_Role control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorEducaPersonale_Role;

		/// <summary>
		/// RbEducaPersonale_Role control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbEducaPersonale_Role;

		/// <summary>
		/// ErrorRBIsRakat control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorRBIsRakat;

		/// <summary>
		/// RBisEhandel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RBisEhandel;

		/// <summary>
		/// panel_Rakat control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panel_Rakat;

		/// <summary>
		/// ErrorRbRakatRole control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadLabel ErrorRbRakatRole;

		/// <summary>
		/// RbEHandelBrugerType control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList RbEHandelBrugerType;

		/// <summary>
		/// panel_rakat_profitomkoststed control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel panel_rakat_profitomkoststed;

		/// <summary>
		/// TxbEHandelProfitCenter control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbEHandelProfitCenter;

		/// <summary>
		/// TxbBemaerkninger control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox TxbBemaerkninger;

		/// <summary>
		/// Button_submit control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton Button_submit;

		/// <summary>
		/// RadAjaxManager1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadAjaxManager RadAjaxManager1;
	}
}
