//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace App_Web.SofdCoreAPI_WebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SofdCoreAPI_WebServiceSoap", Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class SofdCoreAPI_WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPersons_FromUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersons_FromCPROperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersons_FromEmployeeIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrgUnitFromUuidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPersonsWithADUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonsWithoutADUsersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SofdCoreAPI_WebService() {
            this.Url = global::App_Web.Properties.Settings.Default.App_Web_SofdCoreAPI_WebService_SofdCoreAPI_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPersons_FromUsernameCompletedEventHandler GetPersons_FromUsernameCompleted;
        
        /// <remarks/>
        public event GetPersons_FromCPRCompletedEventHandler GetPersons_FromCPRCompleted;
        
        /// <remarks/>
        public event GetPersons_FromEmployeeIDCompletedEventHandler GetPersons_FromEmployeeIDCompleted;
        
        /// <remarks/>
        public event GetOrgUnitFromUuidCompletedEventHandler GetOrgUnitFromUuidCompleted;
        
        /// <remarks/>
        public event GetAllPersonsWithADUsernameCompletedEventHandler GetAllPersonsWithADUsernameCompleted;
        
        /// <remarks/>
        public event GetPersonsWithoutADUsersCompletedEventHandler GetPersonsWithoutADUsersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Skanderborg.dk/xml/Schemas/GetPersons_FromUsername", RequestNamespace="http://Skanderborg.dk/xml/Schemas", ResponseNamespace="http://Skanderborg.dk/xml/Schemas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Person[] GetPersons_FromUsername(string username, string sofdCoreApiKey) {
            object[] results = this.Invoke("GetPersons_FromUsername", new object[] {
                        username,
                        sofdCoreApiKey});
            return ((Person[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPersons_FromUsernameAsync(string username, string sofdCoreApiKey) {
            this.GetPersons_FromUsernameAsync(username, sofdCoreApiKey, null);
        }
        
        /// <remarks/>
        public void GetPersons_FromUsernameAsync(string username, string sofdCoreApiKey, object userState) {
            if ((this.GetPersons_FromUsernameOperationCompleted == null)) {
                this.GetPersons_FromUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersons_FromUsernameOperationCompleted);
            }
            this.InvokeAsync("GetPersons_FromUsername", new object[] {
                        username,
                        sofdCoreApiKey}, this.GetPersons_FromUsernameOperationCompleted, userState);
        }
        
        private void OnGetPersons_FromUsernameOperationCompleted(object arg) {
            if ((this.GetPersons_FromUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersons_FromUsernameCompleted(this, new GetPersons_FromUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Skanderborg.dk/xml/Schemas/GetPersons_FromCPR", RequestNamespace="http://Skanderborg.dk/xml/Schemas", ResponseNamespace="http://Skanderborg.dk/xml/Schemas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Person[] GetPersons_FromCPR(string cpr, string sofdCoreApiKey) {
            object[] results = this.Invoke("GetPersons_FromCPR", new object[] {
                        cpr,
                        sofdCoreApiKey});
            return ((Person[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPersons_FromCPRAsync(string cpr, string sofdCoreApiKey) {
            this.GetPersons_FromCPRAsync(cpr, sofdCoreApiKey, null);
        }
        
        /// <remarks/>
        public void GetPersons_FromCPRAsync(string cpr, string sofdCoreApiKey, object userState) {
            if ((this.GetPersons_FromCPROperationCompleted == null)) {
                this.GetPersons_FromCPROperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersons_FromCPROperationCompleted);
            }
            this.InvokeAsync("GetPersons_FromCPR", new object[] {
                        cpr,
                        sofdCoreApiKey}, this.GetPersons_FromCPROperationCompleted, userState);
        }
        
        private void OnGetPersons_FromCPROperationCompleted(object arg) {
            if ((this.GetPersons_FromCPRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersons_FromCPRCompleted(this, new GetPersons_FromCPRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Skanderborg.dk/xml/Schemas/GetPersons_FromEmployeeID", RequestNamespace="http://Skanderborg.dk/xml/Schemas", ResponseNamespace="http://Skanderborg.dk/xml/Schemas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Person[] GetPersons_FromEmployeeID(string employeeID, string sofdCoreApiKey) {
            object[] results = this.Invoke("GetPersons_FromEmployeeID", new object[] {
                        employeeID,
                        sofdCoreApiKey});
            return ((Person[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPersons_FromEmployeeIDAsync(string employeeID, string sofdCoreApiKey) {
            this.GetPersons_FromEmployeeIDAsync(employeeID, sofdCoreApiKey, null);
        }
        
        /// <remarks/>
        public void GetPersons_FromEmployeeIDAsync(string employeeID, string sofdCoreApiKey, object userState) {
            if ((this.GetPersons_FromEmployeeIDOperationCompleted == null)) {
                this.GetPersons_FromEmployeeIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersons_FromEmployeeIDOperationCompleted);
            }
            this.InvokeAsync("GetPersons_FromEmployeeID", new object[] {
                        employeeID,
                        sofdCoreApiKey}, this.GetPersons_FromEmployeeIDOperationCompleted, userState);
        }
        
        private void OnGetPersons_FromEmployeeIDOperationCompleted(object arg) {
            if ((this.GetPersons_FromEmployeeIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersons_FromEmployeeIDCompleted(this, new GetPersons_FromEmployeeIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Skanderborg.dk/xml/Schemas/GetOrgUnitFromUuid", RequestNamespace="http://Skanderborg.dk/xml/Schemas", ResponseNamespace="http://Skanderborg.dk/xml/Schemas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrgUnit[] GetOrgUnitFromUuid(string orgUuid, string sofdCoreApiKey) {
            object[] results = this.Invoke("GetOrgUnitFromUuid", new object[] {
                        orgUuid,
                        sofdCoreApiKey});
            return ((OrgUnit[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrgUnitFromUuidAsync(string orgUuid, string sofdCoreApiKey) {
            this.GetOrgUnitFromUuidAsync(orgUuid, sofdCoreApiKey, null);
        }
        
        /// <remarks/>
        public void GetOrgUnitFromUuidAsync(string orgUuid, string sofdCoreApiKey, object userState) {
            if ((this.GetOrgUnitFromUuidOperationCompleted == null)) {
                this.GetOrgUnitFromUuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrgUnitFromUuidOperationCompleted);
            }
            this.InvokeAsync("GetOrgUnitFromUuid", new object[] {
                        orgUuid,
                        sofdCoreApiKey}, this.GetOrgUnitFromUuidOperationCompleted, userState);
        }
        
        private void OnGetOrgUnitFromUuidOperationCompleted(object arg) {
            if ((this.GetOrgUnitFromUuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrgUnitFromUuidCompleted(this, new GetOrgUnitFromUuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Skanderborg.dk/xml/Schemas/GetAllPersonsWithADUsername", RequestNamespace="http://Skanderborg.dk/xml/Schemas", ResponseNamespace="http://Skanderborg.dk/xml/Schemas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Person[] GetAllPersonsWithADUsername(string sofdCoreApiKey) {
            object[] results = this.Invoke("GetAllPersonsWithADUsername", new object[] {
                        sofdCoreApiKey});
            return ((Person[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPersonsWithADUsernameAsync(string sofdCoreApiKey) {
            this.GetAllPersonsWithADUsernameAsync(sofdCoreApiKey, null);
        }
        
        /// <remarks/>
        public void GetAllPersonsWithADUsernameAsync(string sofdCoreApiKey, object userState) {
            if ((this.GetAllPersonsWithADUsernameOperationCompleted == null)) {
                this.GetAllPersonsWithADUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPersonsWithADUsernameOperationCompleted);
            }
            this.InvokeAsync("GetAllPersonsWithADUsername", new object[] {
                        sofdCoreApiKey}, this.GetAllPersonsWithADUsernameOperationCompleted, userState);
        }
        
        private void OnGetAllPersonsWithADUsernameOperationCompleted(object arg) {
            if ((this.GetAllPersonsWithADUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPersonsWithADUsernameCompleted(this, new GetAllPersonsWithADUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Skanderborg.dk/xml/Schemas/GetPersonsWithoutADUsers", RequestNamespace="http://Skanderborg.dk/xml/Schemas", ResponseNamespace="http://Skanderborg.dk/xml/Schemas", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmployeeAffiliationWithoutADUser[] GetPersonsWithoutADUsers(string sofdCoreApiKey) {
            object[] results = this.Invoke("GetPersonsWithoutADUsers", new object[] {
                        sofdCoreApiKey});
            return ((EmployeeAffiliationWithoutADUser[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonsWithoutADUsersAsync(string sofdCoreApiKey) {
            this.GetPersonsWithoutADUsersAsync(sofdCoreApiKey, null);
        }
        
        /// <remarks/>
        public void GetPersonsWithoutADUsersAsync(string sofdCoreApiKey, object userState) {
            if ((this.GetPersonsWithoutADUsersOperationCompleted == null)) {
                this.GetPersonsWithoutADUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonsWithoutADUsersOperationCompleted);
            }
            this.InvokeAsync("GetPersonsWithoutADUsers", new object[] {
                        sofdCoreApiKey}, this.GetPersonsWithoutADUsersOperationCompleted, userState);
        }
        
        private void OnGetPersonsWithoutADUsersOperationCompleted(object arg) {
            if ((this.GetPersonsWithoutADUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonsWithoutADUsersCompleted(this, new GetPersonsWithoutADUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class Person {
        
        private string uuidField;
        
        private string masterField;
        
        private System.Nullable<bool> deletedField;
        
        private System.DateTime createdField;
        
        private System.Nullable<System.DateTime> lastChangedField;
        
        private string firstnameField;
        
        private string surnameField;
        
        private string cprField;
        
        private string chosenNameField;
        
        private System.Nullable<System.DateTime> anniversaryDateField;
        
        private string localExtensionsField;
        
        private System.Nullable<long> registeredPostAddressIdField;
        
        private System.Nullable<long> residencePostAddressIdField;
        
        private string keyWordsField;
        
        private string notesField;
        
        private System.Nullable<bool> taxedPhoneField;
        
        private System.Nullable<bool> disableAccountOrdersField;
        
        private System.Nullable<bool> forceStopField;
        
        private string calculatedNameField;
        
        private Affiliation[] affiliationsField;
        
        private User[] usersField;
        
        private PersonPost registeredPostAddressField;
        
        private PersonPost residencePostAddressField;
        
        private AuthorizationCode[] authorizationCodesField;
        
        private Leave leaveField;
        
        private PersonPhone[] phonesField;
        
        private PersonChild[] childrenField;
        
        private PersonPhone[] phonesPhonesField;
        
        private DisabledUser[] disabledUsersField;
        
        private SubstituteAssignment[] substitutesField;
        
        private Photo photoField;
        
        /// <remarks/>
        public string Uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastChanged {
            get {
                return this.lastChangedField;
            }
            set {
                this.lastChangedField = value;
            }
        }
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string Cpr {
            get {
                return this.cprField;
            }
            set {
                this.cprField = value;
            }
        }
        
        /// <remarks/>
        public string ChosenName {
            get {
                return this.chosenNameField;
            }
            set {
                this.chosenNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AnniversaryDate {
            get {
                return this.anniversaryDateField;
            }
            set {
                this.anniversaryDateField = value;
            }
        }
        
        /// <remarks/>
        public string LocalExtensions {
            get {
                return this.localExtensionsField;
            }
            set {
                this.localExtensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> RegisteredPostAddressId {
            get {
                return this.registeredPostAddressIdField;
            }
            set {
                this.registeredPostAddressIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> ResidencePostAddressId {
            get {
                return this.residencePostAddressIdField;
            }
            set {
                this.residencePostAddressIdField = value;
            }
        }
        
        /// <remarks/>
        public string KeyWords {
            get {
                return this.keyWordsField;
            }
            set {
                this.keyWordsField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> TaxedPhone {
            get {
                return this.taxedPhoneField;
            }
            set {
                this.taxedPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> DisableAccountOrders {
            get {
                return this.disableAccountOrdersField;
            }
            set {
                this.disableAccountOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ForceStop {
            get {
                return this.forceStopField;
            }
            set {
                this.forceStopField = value;
            }
        }
        
        /// <remarks/>
        public string CalculatedName {
            get {
                return this.calculatedNameField;
            }
            set {
                this.calculatedNameField = value;
            }
        }
        
        /// <remarks/>
        public Affiliation[] Affiliations {
            get {
                return this.affiliationsField;
            }
            set {
                this.affiliationsField = value;
            }
        }
        
        /// <remarks/>
        public User[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        public PersonPost RegisteredPostAddress {
            get {
                return this.registeredPostAddressField;
            }
            set {
                this.registeredPostAddressField = value;
            }
        }
        
        /// <remarks/>
        public PersonPost ResidencePostAddress {
            get {
                return this.residencePostAddressField;
            }
            set {
                this.residencePostAddressField = value;
            }
        }
        
        /// <remarks/>
        public AuthorizationCode[] AuthorizationCodes {
            get {
                return this.authorizationCodesField;
            }
            set {
                this.authorizationCodesField = value;
            }
        }
        
        /// <remarks/>
        public Leave Leave {
            get {
                return this.leaveField;
            }
            set {
                this.leaveField = value;
            }
        }
        
        /// <remarks/>
        public PersonPhone[] Phones {
            get {
                return this.phonesField;
            }
            set {
                this.phonesField = value;
            }
        }
        
        /// <remarks/>
        public PersonChild[] Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        public PersonPhone[] PhonesPhones {
            get {
                return this.phonesPhonesField;
            }
            set {
                this.phonesPhonesField = value;
            }
        }
        
        /// <remarks/>
        public DisabledUser[] DisabledUsers {
            get {
                return this.disabledUsersField;
            }
            set {
                this.disabledUsersField = value;
            }
        }
        
        /// <remarks/>
        public SubstituteAssignment[] Substitutes {
            get {
                return this.substitutesField;
            }
            set {
                this.substitutesField = value;
            }
        }
        
        /// <remarks/>
        public Photo Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class Affiliation {
        
        private string uuidField;
        
        private string masterField;
        
        private string masterIdField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private System.Nullable<System.DateTime> stopDateField;
        
        private System.Nullable<bool> deletedField;
        
        private string employeeIdField;
        
        private string employmentTermsField;
        
        private string employmentTermsTextField;
        
        private string payGradeField;
        
        private string wageStepField;
        
        private System.Nullable<double> workingHoursDenominatorField;
        
        private System.Nullable<double> workingHoursNumeratorField;
        
        private string affiliationTypeField;
        
        private string localExtensionsField;
        
        private string positionIdField;
        
        private string positionNameField;
        
        private System.Nullable<bool> primeField;
        
        private string positionTypeIdField;
        
        private string positionTypeNameField;
        
        private string personUuidField;
        
        private string orgunitUuidField;
        
        private string sourceOrgunitUuidField;
        
        private string alternativeOrgunitUuidField;
        
        private OrgUnit orgUnitField;
        
        private Function[] functionsField;
        
        /// <remarks/>
        public string Uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        public string MasterId {
            get {
                return this.masterIdField;
            }
            set {
                this.masterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StopDate {
            get {
                return this.stopDateField;
            }
            set {
                this.stopDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        public string EmploymentTerms {
            get {
                return this.employmentTermsField;
            }
            set {
                this.employmentTermsField = value;
            }
        }
        
        /// <remarks/>
        public string EmploymentTermsText {
            get {
                return this.employmentTermsTextField;
            }
            set {
                this.employmentTermsTextField = value;
            }
        }
        
        /// <remarks/>
        public string PayGrade {
            get {
                return this.payGradeField;
            }
            set {
                this.payGradeField = value;
            }
        }
        
        /// <remarks/>
        public string WageStep {
            get {
                return this.wageStepField;
            }
            set {
                this.wageStepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> WorkingHoursDenominator {
            get {
                return this.workingHoursDenominatorField;
            }
            set {
                this.workingHoursDenominatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> WorkingHoursNumerator {
            get {
                return this.workingHoursNumeratorField;
            }
            set {
                this.workingHoursNumeratorField = value;
            }
        }
        
        /// <remarks/>
        public string AffiliationType {
            get {
                return this.affiliationTypeField;
            }
            set {
                this.affiliationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LocalExtensions {
            get {
                return this.localExtensionsField;
            }
            set {
                this.localExtensionsField = value;
            }
        }
        
        /// <remarks/>
        public string PositionId {
            get {
                return this.positionIdField;
            }
            set {
                this.positionIdField = value;
            }
        }
        
        /// <remarks/>
        public string PositionName {
            get {
                return this.positionNameField;
            }
            set {
                this.positionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Prime {
            get {
                return this.primeField;
            }
            set {
                this.primeField = value;
            }
        }
        
        /// <remarks/>
        public string PositionTypeId {
            get {
                return this.positionTypeIdField;
            }
            set {
                this.positionTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string PositionTypeName {
            get {
                return this.positionTypeNameField;
            }
            set {
                this.positionTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
        
        /// <remarks/>
        public string OrgunitUuid {
            get {
                return this.orgunitUuidField;
            }
            set {
                this.orgunitUuidField = value;
            }
        }
        
        /// <remarks/>
        public string SourceOrgunitUuid {
            get {
                return this.sourceOrgunitUuidField;
            }
            set {
                this.sourceOrgunitUuidField = value;
            }
        }
        
        /// <remarks/>
        public string AlternativeOrgunitUuid {
            get {
                return this.alternativeOrgunitUuidField;
            }
            set {
                this.alternativeOrgunitUuidField = value;
            }
        }
        
        /// <remarks/>
        public OrgUnit OrgUnit {
            get {
                return this.orgUnitField;
            }
            set {
                this.orgUnitField = value;
            }
        }
        
        /// <remarks/>
        public Function[] Functions {
            get {
                return this.functionsField;
            }
            set {
                this.functionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class OrgUnit {
        
        private string uuidField;
        
        private int idField;
        
        private string masterField;
        
        private string masterIdField;
        
        private System.Nullable<bool> deletedField;
        
        private System.Nullable<System.DateTime> createdField;
        
        private System.Nullable<System.DateTime> lastChangedField;
        
        private string parentUuidField;
        
        private string shortnameField;
        
        private string nameField;
        
        private string displayNameField;
        
        private string sourceNameField;
        
        private string cvrNameField;
        
        private System.Nullable<long> cvrField;
        
        private System.Nullable<long> eanField;
        
        private System.Nullable<bool> eanInheritedField;
        
        private System.Nullable<long> senrField;
        
        private System.Nullable<long> pnrField;
        
        private string costBearerField;
        
        private string orgTypeField;
        
        private System.Nullable<long> orgTypeIdField;
        
        private string localExtensionsField;
        
        private string keyWordsField;
        
        private string openingHoursField;
        
        private string notesField;
        
        private string emailField;
        
        private OrgUnitPost[] addressesField;
        
        private OrgUnitManager managerField;
        
        private OrgUnitKLEPrimary[] kLEPrimaryField;
        
        private OrgUnitKLESecondary[] kLESecondaryField;
        
        private OrgUnitTag[] tagsField;
        
        private OrgUnitPhone[] phonesField;
        
        /// <remarks/>
        public string Uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        public string MasterId {
            get {
                return this.masterIdField;
            }
            set {
                this.masterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastChanged {
            get {
                return this.lastChangedField;
            }
            set {
                this.lastChangedField = value;
            }
        }
        
        /// <remarks/>
        public string ParentUuid {
            get {
                return this.parentUuidField;
            }
            set {
                this.parentUuidField = value;
            }
        }
        
        /// <remarks/>
        public string Shortname {
            get {
                return this.shortnameField;
            }
            set {
                this.shortnameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string SourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        public string CvrName {
            get {
                return this.cvrNameField;
            }
            set {
                this.cvrNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Cvr {
            get {
                return this.cvrField;
            }
            set {
                this.cvrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Ean {
            get {
                return this.eanField;
            }
            set {
                this.eanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> EanInherited {
            get {
                return this.eanInheritedField;
            }
            set {
                this.eanInheritedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Senr {
            get {
                return this.senrField;
            }
            set {
                this.senrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Pnr {
            get {
                return this.pnrField;
            }
            set {
                this.pnrField = value;
            }
        }
        
        /// <remarks/>
        public string CostBearer {
            get {
                return this.costBearerField;
            }
            set {
                this.costBearerField = value;
            }
        }
        
        /// <remarks/>
        public string OrgType {
            get {
                return this.orgTypeField;
            }
            set {
                this.orgTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> OrgTypeId {
            get {
                return this.orgTypeIdField;
            }
            set {
                this.orgTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string LocalExtensions {
            get {
                return this.localExtensionsField;
            }
            set {
                this.localExtensionsField = value;
            }
        }
        
        /// <remarks/>
        public string KeyWords {
            get {
                return this.keyWordsField;
            }
            set {
                this.keyWordsField = value;
            }
        }
        
        /// <remarks/>
        public string OpeningHours {
            get {
                return this.openingHoursField;
            }
            set {
                this.openingHoursField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public OrgUnitPost[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        public OrgUnitManager Manager {
            get {
                return this.managerField;
            }
            set {
                this.managerField = value;
            }
        }
        
        /// <remarks/>
        public OrgUnitKLEPrimary[] KLEPrimary {
            get {
                return this.kLEPrimaryField;
            }
            set {
                this.kLEPrimaryField = value;
            }
        }
        
        /// <remarks/>
        public OrgUnitKLESecondary[] KLESecondary {
            get {
                return this.kLESecondaryField;
            }
            set {
                this.kLESecondaryField = value;
            }
        }
        
        /// <remarks/>
        public OrgUnitTag[] Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public OrgUnitPhone[] Phones {
            get {
                return this.phonesField;
            }
            set {
                this.phonesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class OrgUnitPost {
        
        private string orgUnitUuidField;
        
        private long idField;
        
        private bool primeField;
        
        private string streetField;
        
        private string localnameField;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string countryField;
        
        private bool addressProtectedField;
        
        private string masterField;
        
        private string masterIdField;
        
        /// <remarks/>
        public string OrgUnitUuid {
            get {
                return this.orgUnitUuidField;
            }
            set {
                this.orgUnitUuidField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool Prime {
            get {
                return this.primeField;
            }
            set {
                this.primeField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string Localname {
            get {
                return this.localnameField;
            }
            set {
                this.localnameField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public bool AddressProtected {
            get {
                return this.addressProtectedField;
            }
            set {
                this.addressProtectedField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        public string MasterId {
            get {
                return this.masterIdField;
            }
            set {
                this.masterIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class EmployeeAffiliationWithoutADUser {
        
        private string employeeIdField;
        
        private string personFirstnameField;
        
        private string personSurnameField;
        
        private string personCprField;
        
        private string affliationPositionNameField;
        
        private string orgUnitNameField;
        
        /// <remarks/>
        public string EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        public string PersonFirstname {
            get {
                return this.personFirstnameField;
            }
            set {
                this.personFirstnameField = value;
            }
        }
        
        /// <remarks/>
        public string PersonSurname {
            get {
                return this.personSurnameField;
            }
            set {
                this.personSurnameField = value;
            }
        }
        
        /// <remarks/>
        public string PersonCpr {
            get {
                return this.personCprField;
            }
            set {
                this.personCprField = value;
            }
        }
        
        /// <remarks/>
        public string AffliationPositionName {
            get {
                return this.affliationPositionNameField;
            }
            set {
                this.affliationPositionNameField = value;
            }
        }
        
        /// <remarks/>
        public string OrgUnitName {
            get {
                return this.orgUnitNameField;
            }
            set {
                this.orgUnitNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class Photo {
        
        private long idField;
        
        private string personUuidField;
        
        private System.DateTime lastChangedField;
        
        private long checksumField;
        
        private string formatField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastChanged {
            get {
                return this.lastChangedField;
            }
            set {
                this.lastChangedField = value;
            }
        }
        
        /// <remarks/>
        public long Checksum {
            get {
                return this.checksumField;
            }
            set {
                this.checksumField = value;
            }
        }
        
        /// <remarks/>
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class SubstituteAssignment {
        
        private long idField;
        
        private string personUuidField;
        
        private string substituteUuidField;
        
        private string substituteContextNameField;
        
        private string substituteContextIdentifierField;
        
        private bool substituteContextSupportsConstraintsField;
        
        private System.DateTime createdField;
        
        private System.DateTime changedField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
        
        /// <remarks/>
        public string SubstituteUuid {
            get {
                return this.substituteUuidField;
            }
            set {
                this.substituteUuidField = value;
            }
        }
        
        /// <remarks/>
        public string SubstituteContextName {
            get {
                return this.substituteContextNameField;
            }
            set {
                this.substituteContextNameField = value;
            }
        }
        
        /// <remarks/>
        public string SubstituteContextIdentifier {
            get {
                return this.substituteContextIdentifierField;
            }
            set {
                this.substituteContextIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public bool SubstituteContextSupportsConstraints {
            get {
                return this.substituteContextSupportsConstraintsField;
            }
            set {
                this.substituteContextSupportsConstraintsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class DisabledUser {
        
        private string uuidField;
        
        private string masterField;
        
        private string masterIdField;
        
        private string userIdField;
        
        private string localExtensionsField;
        
        private string userTypeField;
        
        private bool primeField;
        
        private string employeeIdField;
        
        private string personUuidField;
        
        /// <remarks/>
        public string Uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        public string MasterId {
            get {
                return this.masterIdField;
            }
            set {
                this.masterIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string LocalExtensions {
            get {
                return this.localExtensionsField;
            }
            set {
                this.localExtensionsField = value;
            }
        }
        
        /// <remarks/>
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool Prime {
            get {
                return this.primeField;
            }
            set {
                this.primeField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class PersonChild {
        
        private int refIdField;
        
        private string cprField;
        
        private string nameField;
        
        private string personUuidField;
        
        /// <remarks/>
        public int RefId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
        
        /// <remarks/>
        public string Cpr {
            get {
                return this.cprField;
            }
            set {
                this.cprField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class PersonPhone {
        
        private string personUuidField;
        
        private long idField;
        
        private System.Nullable<bool> primeField;
        
        private System.Nullable<bool> typePrimeField;
        
        private string phoneNumberField;
        
        private string phoneTypeField;
        
        private string masterField;
        
        private string masterIdField;
        
        private string notesField;
        
        private string visibilityField;
        
        private string functionTypeField;
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Prime {
            get {
                return this.primeField;
            }
            set {
                this.primeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> TypePrime {
            get {
                return this.typePrimeField;
            }
            set {
                this.typePrimeField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneType {
            get {
                return this.phoneTypeField;
            }
            set {
                this.phoneTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        public string MasterId {
            get {
                return this.masterIdField;
            }
            set {
                this.masterIdField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public string Visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        public string FunctionType {
            get {
                return this.functionTypeField;
            }
            set {
                this.functionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class Leave {
        
        private long idField;
        
        private string personUuidField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private System.Nullable<System.DateTime> stopDateField;
        
        private string reasonField;
        
        private string reasonTextField;
        
        private System.Nullable<bool> disableAccountOrdersField;
        
        private System.Nullable<bool> expireAccountsField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StopDate {
            get {
                return this.stopDateField;
            }
            set {
                this.stopDateField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public string ReasonText {
            get {
                return this.reasonTextField;
            }
            set {
                this.reasonTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> DisableAccountOrders {
            get {
                return this.disableAccountOrdersField;
            }
            set {
                this.disableAccountOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ExpireAccounts {
            get {
                return this.expireAccountsField;
            }
            set {
                this.expireAccountsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class AuthorizationCode {
        
        private long idField;
        
        private bool primeField;
        
        private string codeField;
        
        private string nameField;
        
        private string personUuidField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool Prime {
            get {
                return this.primeField;
            }
            set {
                this.primeField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class PersonPost {
        
        private System.Nullable<bool> primeField;
        
        private string streetField;
        
        private string localnameField;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string countryField;
        
        private System.Nullable<bool> addressProtectedField;
        
        private string masterField;
        
        private string masterIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Prime {
            get {
                return this.primeField;
            }
            set {
                this.primeField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string Localname {
            get {
                return this.localnameField;
            }
            set {
                this.localnameField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> AddressProtected {
            get {
                return this.addressProtectedField;
            }
            set {
                this.addressProtectedField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        public string MasterId {
            get {
                return this.masterIdField;
            }
            set {
                this.masterIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class User {
        
        private string uuidField;
        
        private string masterField;
        
        private string masterIdField;
        
        private string userIdField;
        
        private string localExtensionsField;
        
        private string userTypeField;
        
        private bool primeField;
        
        private string employeeIdField;
        
        private string kombitUuidField;
        
        private string personUuidField;
        
        /// <remarks/>
        public string Uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        public string MasterId {
            get {
                return this.masterIdField;
            }
            set {
                this.masterIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string LocalExtensions {
            get {
                return this.localExtensionsField;
            }
            set {
                this.localExtensionsField = value;
            }
        }
        
        /// <remarks/>
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool Prime {
            get {
                return this.primeField;
            }
            set {
                this.primeField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        public string KombitUuid {
            get {
                return this.kombitUuidField;
            }
            set {
                this.kombitUuidField = value;
            }
        }
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class Function {
        
        private long idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string categoryField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class OrgUnitPhone {
        
        private string orgUnitUuidField;
        
        private long idField;
        
        private System.Nullable<bool> primeField;
        
        private System.Nullable<bool> typePrimeField;
        
        private string phoneNumberField;
        
        private string phoneTypeField;
        
        private string masterField;
        
        private string masterIdField;
        
        private string notesField;
        
        private string visibilityField;
        
        private string functionTypeField;
        
        /// <remarks/>
        public string OrgUnitUuid {
            get {
                return this.orgUnitUuidField;
            }
            set {
                this.orgUnitUuidField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Prime {
            get {
                return this.primeField;
            }
            set {
                this.primeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> TypePrime {
            get {
                return this.typePrimeField;
            }
            set {
                this.typePrimeField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneType {
            get {
                return this.phoneTypeField;
            }
            set {
                this.phoneTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        public string MasterId {
            get {
                return this.masterIdField;
            }
            set {
                this.masterIdField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public string Visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        public string FunctionType {
            get {
                return this.functionTypeField;
            }
            set {
                this.functionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class OrgUnitTag {
        
        private int refIdField;
        
        private string tagField;
        
        private string customValueField;
        
        private string orgUnitUuidField;
        
        /// <remarks/>
        public int RefId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomValue {
            get {
                return this.customValueField;
            }
            set {
                this.customValueField = value;
            }
        }
        
        /// <remarks/>
        public string OrgUnitUuid {
            get {
                return this.orgUnitUuidField;
            }
            set {
                this.orgUnitUuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class OrgUnitKLESecondary {
        
        private string orgUnitUuidField;
        
        private string codeField;
        
        private string nameField;
        
        private System.Nullable<bool> activeField;
        
        /// <remarks/>
        public string OrgUnitUuid {
            get {
                return this.orgUnitUuidField;
            }
            set {
                this.orgUnitUuidField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class OrgUnitKLEPrimary {
        
        private string orgUnitUuidField;
        
        private string codeField;
        
        private string nameField;
        
        private System.Nullable<bool> activeField;
        
        /// <remarks/>
        public string OrgUnitUuid {
            get {
                return this.orgUnitUuidField;
            }
            set {
                this.orgUnitUuidField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Skanderborg.dk/xml/Schemas")]
    public partial class OrgUnitManager {
        
        private int idField;
        
        private bool inheritedField;
        
        private string nameField;
        
        private string orgUnitUuidField;
        
        private string personUuidField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool Inherited {
            get {
                return this.inheritedField;
            }
            set {
                this.inheritedField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string OrgUnitUuid {
            get {
                return this.orgUnitUuidField;
            }
            set {
                this.orgUnitUuidField = value;
            }
        }
        
        /// <remarks/>
        public string PersonUuid {
            get {
                return this.personUuidField;
            }
            set {
                this.personUuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPersons_FromUsernameCompletedEventHandler(object sender, GetPersons_FromUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersons_FromUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersons_FromUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Person[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Person[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPersons_FromCPRCompletedEventHandler(object sender, GetPersons_FromCPRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersons_FromCPRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersons_FromCPRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Person[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Person[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPersons_FromEmployeeIDCompletedEventHandler(object sender, GetPersons_FromEmployeeIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersons_FromEmployeeIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersons_FromEmployeeIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Person[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Person[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetOrgUnitFromUuidCompletedEventHandler(object sender, GetOrgUnitFromUuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrgUnitFromUuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrgUnitFromUuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrgUnit[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrgUnit[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAllPersonsWithADUsernameCompletedEventHandler(object sender, GetAllPersonsWithADUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPersonsWithADUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPersonsWithADUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Person[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Person[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPersonsWithoutADUsersCompletedEventHandler(object sender, GetPersonsWithoutADUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonsWithoutADUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonsWithoutADUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmployeeAffiliationWithoutADUser[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmployeeAffiliationWithoutADUser[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591